server:
  port: 5000
  servlet:
    context-path: /api
spring:
  mvc:
    static-path-pattern: /upload/**
  resources:
    static-locations: file:src/main/resources/static
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/project_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 2
    lettuce:
      pool:
        max-idle: 30
        min-idle: 10
        max-active: 30
        max-wait: 10000
  mail:
    host: smtp.qq.com
    port: 587
    username: 3216252476@qq.com
    password: puuqglgygxwmdghb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          enable:
            trust: smtp.qq.com

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.project.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
    map-underscore-to-camel-case: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    use-generated-keys: true

